### ISSUE TITLE
Current instructions don't seem to work

### ISSUE THREAD

**Issue by jgerman** [Datomic/codeq#14]
Just a heads up, I wanted to check out the project but following the current instructions doesn't seem to work.

I get a connection error when I try to import a repo. Datomic seems to be running correctly so I'm not sure the problem though I haven't dug in yet. Exception is below:

java -server -Xmx1g -jar ../codeq/target/codeq-0.1.0-SNAPSHOT-standalone.jar datomic:free://localhost:4334/free/git
Exception in thread "main" clojure.lang.ExceptionInfo: Error communicating with HOST localhost on PORT 4334 {:host "localhost", :alt-host nil, :port 4334, :username "x6r830jIopXHuvLeAmwSYRTPjFCtLaGOdLszxzX5t8U=", :password "csuC3mlEEs3ZjHW9+fK5MWJEfx1EeyJToeSd7Yk1nYM=", :timestamp 1364250608163, :version "0.8.3704", :encrypt-channel true}
    at clojure.core$ex_info.invoke(core.clj:4327)
    at datomic.connector$endpoint_error.invoke(connector.clj:43)
    at datomic.connector$create_hornet_factory.invoke(connector.clj:133)
    at datomic.connector$create_connector.invoke(connector.clj:281)
    at datomic.peer$send_admin_request$fn__7657.invoke(peer.clj:448)
    at datomic.peer$send_admin_request.invoke(peer.clj:442)
    at datomic.peer$create_database.invoke(peer.clj:461)
    at clojure.lang.Var.invoke(Var.java:415)
    at datomic.Peer.createDatabase(Peer.java:76)
    at datomic.api$create_database.invoke(api.clj:19)
    at datomic.codeq.core$ensure_db.invoke(core.clj:446)
    at datomic.codeq.core$main.doInvoke(core.clj:530)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:617)
    at datomic.codeq.core$_main.doInvoke(core.clj:539)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at datomic.codeq.core.main(Unknown Source)
Caused by: HornetQException[errorCode=3 message=Timed out waiting to receive cluster topology. Group:null]
    at org.hornetq.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:804)
    at datomic.hornet$create_session_factory.doInvoke(hornet.clj:218)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:619)
    at datomic.connector$try_hornet_connect.invoke(connector.clj:87)
    at datomic.connector$create_hornet_factory.invoke(connector.clj:126)
    ... 14 more

**Comment by alexpw** [comment]
I got this too, when I used datomic 0.8.3664.  I switched to the latest 0.8.4007 and it works fine.

I noticed one difference during start-up, but this could just be added info logging.

Using **0.8.3664**
[codeq-playground:master]$ ./script/start-datomic
'data-dir' property not set, defaulting to 'data' in current directory
'log-dir' property not set, defaulting to 'log' in current directory
Starting datomic:free://localhost:4334/<DB-NAME>, storing data in: data ...
System started datomic:free://localhost:4334/<DB-NAME>, storing data in: data
^C

Using **0.8.4007**
[codeq-playground:master]$ ./script/start-datomic
`Launching with Java options -server -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly`
'data-dir' property not set, defaulting to 'data' in current directory
'log-dir' property not set, defaulting to 'log' in current directory
Starting datomic:free://localhost:4334/<DB-NAME>, storing data in: data ...
System started datomic:free://localhost:4334/<DB-NAME>, storing data in: data

**Comment by jakepearson** [comment]
Hi,
This is happening to lots of laptops at my office in version `0.8.4020.26`.  Here is the stack trace:

```
Exception in thread "main" clojure.lang.ExceptionInfo: Error communicating with HOST localhost on PORT 4334     {:host "localhost", :alt-host nil, :port 4334, :username "C1rGbzPWWFXiJ3+lOucxj9+/A0RakJutYsjsclbu5E8=",     :password "6w0ZOR7jgIIHSKW4vsfYx3llkUshpFp8o4xDAsSK34U=", :timestamp 1374757149710, :version "0.8.4020.26", :encrypt-channel true}
    at clojure.core$ex_info.invoke(core.clj:4327)
    at datomic.connector$endpoint_error.invoke(connector.clj:43)
```

Any ideas would be appreciated.

thanks,
Jake

**Comment by bobby** [comment]
Hi Jake,

General Datomic issues should be reported and discussed on the [Datomic mailing list](https://groups.google.com/forum/#!forum/datomic).

The issue you're seeing probably has to do with the decreased TTL introduced in 0.8.4020 to facilitate faster peer recovery during transactor HA failover.  Sometimes if your transactor is misconfigured such that it has GC pauses longer than 10 seconds, the Peer will disconnect with such an error.

Would you paste the full stacktrace of your issue on a message to the Datomic mailing list?

Thanks,
Bobby
