### ISSUE TITLE
NullPointerException on create a db called git

### ISSUE THREAD

**Issue by tangrammer** [Datomic/codeq#18]
Hi there!
I'm only trying the instructions README

These are the steps I've followed:
- download datomic-free-09.4699
- unzip and cd 
- bin/transactor config/samples/free-transactor-template.properties

`Launching with Java options -server -Xms1g -Xmx1g -XX:NewRatio=4 -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=60 -XX:+UseCMSInitiatingOccupancyOnly -XX:+CMSScavengeBeforeRemark
Starting datomic:free://localhost:4334/<DB-NAME>, storing data in: data ...
System started datomic:free://localhost:4334/<DB-NAME>, storing data in: data`
- git clone https://github.com/Datomic/codeq.git
- cd codeq
- lein uberjar 

```
Implicit AOT of :main will be removed in Leiningen 3.0.0. 
If you only need AOT for your uberjar, consider adding :aot :all into your
:uberjar profile instead.
Compiling datomic.codeq.core
Created /Users/tangrammer/git/codeq/target/codeq-0.1.0-SNAPSHOT.jar
Created /Users/tangrammer/git/codeq/target/codeq-0.1.0-SNAPSHOT-standalone.jar

```
- lein new dat00
- cd dat00
- java -server -Xmx1g -jar ../codeq/target/codeq-0.1.0-SNAPSHOT-standalone.jar datomic:free://localhost:4334/git

```
Exception in thread "main" java.lang.NullPointerException
    at java.util.UUID.fromString(UUID.java:192)
    at datomic.cluster$val_key__GT_uuid.invoke(cluster.clj:21)
    at datomic.log$find_log.invoke(log.clj:526)
    at datomic.peer$load_db_from_basis.invoke(peer.clj:95)
    at datomic.peer.Connection$fn__7316$load_db__7322.invoke(peer.clj:202)
    at datomic.peer.Connection$fn__7316.invoke(peer.clj:203)
    at datomic.peer.Connection.create_connection_state(peer.clj:187)
    at datomic.peer$create_connection$reconnect_fn__7361.invoke(peer.clj:388)
    at datomic.peer$create_connection.invoke(peer.clj:389)
    at datomic.peer$get_connection$fn__7411$fn__7413.invoke(peer.clj:539)
    at datomic.peer$get_connection$fn__7411.invoke(peer.clj:536)
    at datomic.peer$get_connection.invoke(peer.clj:533)
    at datomic.peer$connect_uri.invoke(peer.clj:597)
    at clojure.lang.Var.invoke(Var.java:415)
    at datomic.Peer.connect(Peer.java:74)
    at datomic.api$connect.invoke(api.clj:15)
    at datomic.codeq.core$ensure_db.invoke(core.clj:447)
    at datomic.codeq.core$main.doInvoke(core.clj:530)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:617)
    at datomic.codeq.core$_main.doInvoke(core.clj:539)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at datomic.codeq.core.main(Unknown Source)

```

Then i saw that in Release Notes this note  
*\* Version 0.9.4532 upgrades the database log to format version 2. All peers and transactors in a system must move together to this version or later. **
`bin/datomic revert-to-log-version-1 {your-database-uri}`

Then I tried:
-  bin/datomic revert-to-log-version-1 datomic:free://localhost:4334/git
  But....

```
clojure.lang.ExceptionInfo: :db.error/log-conversion This version of Datomic cannot convert log versions {:db/error :db.error/log-conversion}
    at datomic.error$raise.invoke(error.clj:46)
    at datomic.error$raise.invoke(error.clj:44)
    at datomic.log$convert_log_version.invoke(log.clj:239)
    at datomic.peer$revert_to_log_version_1.invoke(peer.clj:645)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:617)
    at datomic.require$require_and_run.doInvoke(require.clj:22)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at datomic$_main$fn__28.invoke(datomic.clj:139)
    at datomic$_main.doInvoke(datomic.clj:138)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.main$main_opt.invoke(main.clj:335)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at clojure.lang.Var.invoke(Var.java:435)
    at clojure.lang.AFn.applyToHelper(AFn.java:185)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)

```

I'm working with:
- OSX 10.9.2
- `java version "1.7.0_51"
  Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
  Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)`
- Leiningen 2.3.4 on Java 1.7.0_51 Java HotSpot(TM) 64-Bit Server VM

Thanks in advance!
Juan

**Comment by bobby** [comment]
See commit message for de60a9d2df23cc750b1fa4aa4c7d4c2c926a1422.

**Comment by tangrammer** [comment]
Now works fine,

Thanks
